x-root: &root
  stdin_open: true
  tty: true
  build:
    context: ../
    dockerfile: Dockerfile.development
    args:
      NODE_MAJOR: "20"
  environment: &env
    NODE_ENV: ${NODE_ENV:-development}
  tmpfs:
    - /tmp

services:
  root:
    <<: *root
    environment:
      COREPACK_ENABLE_DOWNLOAD_PROMPT: 0
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
      - pnpm-store:/app/.pnpm-store

  frontend:
    <<: *root
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: 4000
      COREPACK_ENABLE_DOWNLOAD_PROMPT: 0
    ports:
      - "4000:4000"
    volumes:
      - .:/app:cached
      - frontend_node_modules:/app/node_modules
      - frontend_pnpm-store:/app/.pnpm-store
    command: pnpm frontend dev -H 0.0.0.0

  backend:
    <<: *root
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: 4001
      COREPACK_ENABLE_DOWNLOAD_PROMPT: 0
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: vistra
      DB_USER: root
      DB_PASSWORD: password
    ports:
      - "4001:4001"
    volumes:
      - .:/app:cached
      - backend_node_modules:/app/node_modules
      - backend_pnpm-store:/app/.pnpm-store
    command: pnpm backend dev -H 0.0.0.0

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=vistra
    volumes:
      - mysql_data:/var/lib/mysql
      - ./packages/backend/sql:/docker-entrypoint-initdb.d

volumes:
  node_modules:
  pnpm-store:
  frontend_node_modules:
  frontend_pnpm-store:
  backend_node_modules:
  backend_pnpm-store:
  mysql_data:
