x-root: &root
  stdin_open: true
  tty: true
  build:
    context: ../
    dockerfile: Dockerfile.development
    args:
      NODE_MAJOR: "20"
  environment: &env
    NODE_ENV: ${NODE_ENV:-development}
  tmpfs:
    - /tmp

services:
  root:
    <<: *root
    environment:
      COREPACK_ENABLE_DOWNLOAD_PROMPT: 0
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
      - pnpm-store:/app/.pnpm-store

volumes:
  node_modules:
  pnpm-store:
